# Generated by Django 5.0.2 on 2024-02-26 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Exuberant_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='correct_option',
        ),
    ]
