# Generated by Django 5.0.2 on 2024-02-26 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exuberant_app', '0002_remove_question_correct_option'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='option',
            name='is_correct',
        ),
        migrations.AddField(
            model_name='option',
            name='sequence',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
    ]
