# Generated by Django 5.0.2 on 2024-02-26 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exuberant_app', '0003_remove_option_is_correct_option_sequence'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='option',
            name='sequence',
        ),
        migrations.AddField(
            model_name='option',
            name='is_correct',
            field=models.BooleanField(default=False),
        ),
    ]
