# Generated by Django 5.0.2 on 2024-02-26 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exuberant_app', '0004_remove_option_sequence_option_is_correct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='option',
            name='is_correct',
        ),
        migrations.AddField(
            model_name='option',
            name='sequence',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
    ]
