# Generated by Django 5.0.2 on 2024-02-26 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exuberant_app', '0005_remove_option_is_correct_option_sequence'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='option',
            constraint=models.UniqueConstraint(condition=models.Q(('sequence__lt', 5)), fields=('question',), name='four_options_per_question'),
        ),
    ]
