# Generated by Django 5.0.2 on 2024-02-26 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exuberant_app', '0006_option_four_options_per_question'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='option',
            name='four_options_per_question',
        ),
        migrations.RemoveField(
            model_name='option',
            name='sequence',
        ),
        migrations.RemoveField(
            model_name='option',
            name='text',
        ),
        migrations.AddField(
            model_name='option',
            name='answer',
            field=models.TextField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='option',
            name='option1',
            field=models.TextField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='option',
            name='option2',
            field=models.TextField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='option',
            name='option3',
            field=models.TextField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='option',
            name='option4',
            field=models.TextField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
