# Generated by Django 5.0.2 on 2024-02-26 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exuberant_app', '0007_remove_option_four_options_per_question_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='text',
            new_name='question',
        ),
        migrations.RemoveField(
            model_name='option',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='option',
            name='option1',
        ),
        migrations.RemoveField(
            model_name='option',
            name='option2',
        ),
        migrations.RemoveField(
            model_name='option',
            name='option3',
        ),
        migrations.RemoveField(
            model_name='option',
            name='option4',
        ),
        migrations.AddField(
            model_name='option',
            name='text',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='answer',
            field=models.TextField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='option1',
            field=models.TextField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='option2',
            field=models.TextField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='option3',
            field=models.TextField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='option4',
            field=models.TextField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
