# Generated by Django 5.0.2 on 2024-02-26 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Exuberant_app', '0008_rename_text_question_question_remove_option_answer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useranswer',
            name='chosen_option',
        ),
        migrations.RemoveField(
            model_name='useranswer',
            name='question',
        ),
        migrations.DeleteModel(
            name='Option',
        ),
        migrations.DeleteModel(
            name='UserAnswer',
        ),
    ]
