# Generated by Django 5.0.2 on 2024-02-26 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exuberant_app', '0011_remove_question_answer_remove_question_option1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='option',
            old_name='text',
            new_name='option1',
        ),
        migrations.RemoveField(
            model_name='useranswer',
            name='chosen_option',
        ),
        migrations.RemoveField(
            model_name='useranswer',
            name='user_id',
        ),
        migrations.AddField(
            model_name='option',
            name='option2',
            field=models.TextField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='option',
            name='option3',
            field=models.TextField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='option',
            name='option4',
            field=models.TextField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='answer',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='useranswer',
            name='answer',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Exuberant_app.option'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='option',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Exuberant_app.question'),
        ),
    ]
