# Generated by Django 5.0.2 on 2024-02-26 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exuberant_app', '0012_rename_text_option_option1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='option',
            old_name='option1',
            new_name='option_text',
        ),
        migrations.RemoveField(
            model_name='option',
            name='option2',
        ),
        migrations.RemoveField(
            model_name='option',
            name='option3',
        ),
        migrations.RemoveField(
            model_name='option',
            name='option4',
        ),
        migrations.AlterField(
            model_name='option',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='Exuberant_app.question'),
        ),
    ]
