# Generated by Django 5.0.2 on 2024-02-26 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exuberant_app', '0014_rename_answer_question_question_text_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userresponse',
            name='selected_option',
        ),
        migrations.AddField(
            model_name='userresponse',
            name='selected_options',
            field=models.ManyToManyField(to='Exuberant_app.option'),
        ),
    ]
