# Generated by Django 5.0.2 on 2024-02-26 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exuberant_app', '0015_remove_userresponse_selected_option_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userresponse',
            name='selected_options',
        ),
        migrations.RemoveField(
            model_name='userresponse',
            name='question',
        ),
        migrations.RemoveField(
            model_name='question',
            name='question_text',
        ),
        migrations.AddField(
            model_name='question',
            name='answer',
            field=models.TextField(default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='question',
            field=models.TextField(default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Option',
        ),
        migrations.DeleteModel(
            name='UserResponse',
        ),
    ]
