# Generated by Django 5.0.2 on 2024-02-26 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exuberant_app', '0017_question_option1_question_option2_question_option3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='correct_option',
            field=models.CharField(choices=[('1', 'Option 1'), ('2', 'Option 2'), ('3', 'Option 3'), ('4', 'Option 4')], default=None, max_length=1),
            preserve_default=False,
        ),
    ]
